### ISSUE TITLE
HEFDOC thoughts

### ISSUE THREAD

**Issue by mon** [nashiora/Haven#1]
Ints - endianness? Make a choice keep it consistent

String: make it UTF-8, keep it simple. Length prefix is fine, make sure it's byte length and not UTF8 chars (easier to parse)

Depending on how insane maps might end up being, perhaps a u32 for tick.measure

Heavently->Heavenly

Leaving only 2 flags unused for the object seems not enough - perhaps make one flag an extended flag that adds an extra byte of flags (to be implemented down the line)

"might be nice to have an index to skip past metadata" - very good idea.

Charter - string array (collab charts)
Level - don't hard force that to 1-20 in case another rescale happens
Music file w/fx - What if I have 2 FX playing at once? Might need to be array
Music volume - use ReplayGain or similar algorithm in the editor so there's some consistency
Preview length - don't think this is required, do the osu approach and play the entire song from preview

**Comment by nashiora** [comment]
Ints: Very likely Big-endian, hadn't doc'd it yet and haven't specified what the encoding is in code either.

String: Will make it UTF-8, byte length of course. Only mentioned that what I'm currently using for completeness, since this is posted alongside the code.

I'm overly attached to using the smallest thing necessary for something, so I'll likely increase the size of more than just measure (maybe division and index could be larger? but 255 seems fine)

I think making the last flag the extended-flags flag would be good, will probably reserve that.

String array for charter is a great idea, thanks.

Level isn't hard forced, tho I guess it looks like that in the current doc. The full range is obviously supported in-file, I should just document that the given range was only "what's currently used, for reference" and not a hard limit.

Multiple music files are something I wanted to ask everyone about, I would LOVE, for example, the ability to give a separate vocal track and only apply laser filters to those so the same idea of multiple music files is awesome.

Music volume: I actually don't know anything about what you mentioned, I can look into that.

Preview length: I don't think it' needed either, but I do state in the docs that it's not required to exist in the file at all and can be left to implementation-defined default values. Implementations can always choose to ignore it as well, so I don't know that removing it is necessary either.

**Comment by mon** [comment]
All sounds good!

ReplayGain is just an automatic loudness characterisation (no idea about licensing there...) as opposed to trusting the mappers to make the right choice on music volume.

**Comment by nashiora** [comment]
Gotcha, can look into now that I'm aware of it thanks!
